set echo on

-- 清空环境
drop table DT_TRAINING_DATA  IF  EXISTS;
drop model DT_MODEL IF  EXISTS;
drop model DT_MODEL_NEW IF  EXISTS;

CREATE TABLE DT_TRAINING_DATA(LABEL DOUBLE, FEATURES DOUBLE ARRAY);

INSERT INTO DT_TRAINING_DATA VALUES
 (0, ARRAY[1, 0, 0]),
 (0, ARRAY[2, 0, 0]),
 (0, ARRAY[3, 0, 0]),
 (0, ARRAY[4, 0, 0]),
 (1, ARRAY[0, 1, 0]),
 (1, ARRAY[0, 2, 0]),
 (1, ARRAY[0, 3, 0]),
 (1, ARRAY[0, 4, 0]),
 (2, ARRAY[0, 0, 1]),
 (2, ARRAY[0, 0, 2]),
 (2, ARRAY[0, 0, 3]),
 (2, ARRAY[0, 0, 4]);
 
CREATE MODEL DT_MODEL AS DECISION_TREE_TRAIN(DT_TRAINING_DATA);

desc model DT_MODEL;

CREATE MODEL PUBLIC.DT_MODEL_NEW LIKE PUBLIC.DT_MODEL WITH DATA;

desc model DT_MODEL_NEW;