--Description: stream jdbc(mysql) source performance
--Date：2020-07-20
--Author：丁婷

drop stream if exists S_MYSQL_SINK_PER_001;
drop stream if exists S_KAFKA_TO_MYSQL_PER_001;

CREATE stream S_KAFKA_TO_MYSQL_PER_001(
TS_15M VARCHAR(17),
MSISDN BIGINT,
IMEI BIGINT,
IMSI BIGINT,
MCC INTEGER,
MNC INTEGER,
LAC INTEGER,
CELL BIGINT,
HOST VARCHAR(128),
URI VARCHAR(10240),
L7REQ VARCHAR(1024),
L7REP VARCHAR(1024),
LATITUDE VARCHAR(16),
LONGITUDE VARCHAR(16),
CILENTBYTE BIGINT,
SERVERBYTE BIGINT,
CLIENTFIRSTSEC BIGINT,
SERVERFIRSTSEC BIGINT,
CLIENTLASTSEC BIGINT,
SERVERLASTSEC BIGINT,
CLIENTIPTO VARCHAR(128),
SERVERIPTO VARCHAR(128),
CLIENTIP VARCHAR(128),
SERVERIP VARCHAR(128),
ctime timestamp
)properties(
 'type': 'source',
 'connector': 'kafka',
 'version': 'universal',
 'topic': 'pertest_1Y',
 'group.id': 'random_str',
 'bootstrap.servers': 'node10:9092',
 'format':'csv',
 'separator':','
);

create stream S_MYSQL_SINK_PER_001 (
TS_15M VARCHAR(17),
MSISDN BIGINT,
IMEI BIGINT,
IMSI BIGINT,
MCC INTEGER,
MNC INTEGER,
LAC INTEGER,
CELL BIGINT,
HOST VARCHAR(128),
URI VARCHAR(10240),
L7REQ VARCHAR(1024),
L7REP VARCHAR(1024),
LATITUDE VARCHAR(16),
LONGITUDE VARCHAR(16),
CILENTBYTE BIGINT,
SERVERBYTE BIGINT,
CLIENTFIRSTSEC BIGINT,
SERVERFIRSTSEC BIGINT,
CLIENTLASTSEC BIGINT,
SERVERLASTSEC BIGINT,
CLIENTIPTO VARCHAR(128),
SERVERIPTO VARCHAR(128),
CLIENTIP VARCHAR(128),
SERVERIP VARCHAR(128),
ctime timestamp
) PROPERTIES (
'type': 'sink',
'connector': 'jdbc',
'tableName': 'MYSQL_PERFORMANCE_001',
'driver': 'com.mysql.jdbc.Driver',
'dbUrl': 'jdbc:mysql://node72:3306/jmeter_istreamsql',
'username': 'test',
'password': '123456',
'batchSize': '10000'
);

set session STREAM_EXECUTE_PARALLELISM 20;

INSERT INTO S_MYSQL_SINK_PER_001 SELECT * FROM S_KAFKA_TO_MYSQL_PER_001;