-- 删除表
DROP TABLE T_PART_BUC_1 IF EXISTS;
DROP TABLE T_PART_BUC_2 IF EXISTS;
DROP TABLE T_PART_BUC_3 IF EXISTS;
DROP TABLE T_PART_BUC_4 IF EXISTS;
DROP TABLE T_PART_BUC_5 IF EXISTS;
DROP TABLE T_PART_BUC_6 IF EXISTS;
DROP TABLE T_BUC_PART_1 IF EXISTS;
DROP TABLE T_PART_NUMERIC IF EXISTS;
DROP TABLE T_PART_REAL IF EXISTS;
DROP TABLE T_PART_SMALLINT IF EXISTS;
DROP TABLE T_BUC_PART_SORT IF EXISTS;

-- 先分区再分桶
-- 分区分桶使用相同的字段
-- 创建分区分桶表
CREATE TABLE T_PART_BUC_1 (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A) CLUSTERED BY (A) INTO 4 BUCKETS;
CREATE TABLE T_PART_BUC_4 (A SMALLINT, B INT, C BOOLEAN, D CHAR(30)) PARTITIONED BY (A, B, C) CLUSTERED BY (A) INTO 4 BUCKETS;
CREATE TABLE T_PART_BUC_5 (A SMALLINT, B INT, C BOOLEAN, D CHAR(30)) PARTITIONED BY (A) CLUSTERED BY (A, B, C) INTO 4 BUCKETS;

-- 分区分桶使用不同的字段
-- 创建分区分桶表
CREATE TABLE T_PART_BUC_2 (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A) CLUSTERED BY (B) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_BUC_2;
-- 查看系统表中该表的分区分桶字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_BUC_2';
-- 插入数据
INSERT INTO T_PART_BUC_2 SELECT TSMALLINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_BUC_2
SELECT * FROM T_PART_BUC_2;

-- 创建分区分桶表
CREATE TABLE T_PART_BUC_3 (A SMALLINT, B INT, C BOOLEAN) PARTITIONED BY (A, C) CLUSTERED BY (B) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_BUC_3;
-- 查看系统表中该表的分区分桶字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_BUC_3';
-- 插入数据
INSERT INTO T_PART_BUC_3 SELECT TSMALLINT, TINT, TBOOL FROM EX_PART_BUC;
-- 查询表T_PART_BUC_3
SELECT * FROM T_PART_BUC_3;

-- 创建分区分桶表
CREATE TABLE T_PART_BUC_6 (A SMALLINT, B INT, C BOOLEAN, D CHAR(30)) PARTITIONED BY (A, B) CLUSTERED BY (C, D) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_BUC_6;
-- 查看系统表中该表的分区分桶字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_BUC_6';
-- 插入数据
INSERT INTO T_PART_BUC_6 SELECT TSMALLINT, TINT, TBOOL, TCHAR FROM EX_PART_BUC;
-- 查询表T_PART_BUC_6
SELECT * FROM T_PART_BUC_6;

-- 先分桶再分区(结果和先分区再分桶一样?)
-- 分区分桶使用不同的字段
-- 创建分区分桶表
CREATE TABLE T_BUC_PART_1 (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (B) INTO 4 BUCKETS PARTITIONED BY (A);
-- 查看创建表的ddl（和建表语句不一致先分区再分桶）
SHOW CREATE TABLE T_BUC_PART_1;
-- 查看系统表中该表的分区分桶字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_BUC_PART_1';
-- 插入数据
INSERT INTO T_BUC_PART_1 SELECT TSMALLINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_PART_1
SELECT * FROM T_BUC_PART_1;

-- 分区分桶使用相同的字段
-- 创建分区分桶表
CREATE TABLE T_BUC_PART_2 (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) INTO 4 BUCKETS PARTITIONED BY (A);

-- 创建排序分区分桶表
CREATE TABLE T_BUC_PART_SORT (A INT, B BOOLEAN, C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 4 BUCKETS PARTITIONED BY (B);
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_PART_SORT;
-- 查看系统表中该表的分区分桶字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_BUC_PART_SORT';
-- 插入数据
INSERT INTO T_BUC_PART_SORT SELECT TINT, TBOOL, TVARCHAR FROM EX_PART_BUC;
-- 查询表
SELECT * FROM T_BUC_PART_SORT;


