--Description:partition
--Date：2020-06-30
--Author：阮娜

SET ECHO ON
SET TIMING ON

-- 删除视图
DROP VIEW V_BUC IF EXISTS;
DROP VIEW V_BUC_1 IF EXISTS;
-- 删除表
DROP TABLE T_BUC IF EXISTS;
DROP TABLE T_BUC_INT IF EXISTS;
DROP TABLE T_BUC_BOOLEAN IF EXISTS;
DROP TABLE T_BUC_CHAR IF EXISTS;
DROP TABLE T_BUC_DATE IF EXISTS;
DROP TABLE T_BUC_DECIMAL IF EXISTS;
DROP TABLE T_BUC_DOUBLE IF EXISTS;
DROP TABLE T_BUC_FLOAT IF EXISTS;
DROP TABLE T_BUC_NUMERIC IF EXISTS;
DROP TABLE T_BUC_REAL IF EXISTS;
DROP TABLE T_BUC_SMALLINT IF EXISTS;
DROP TABLE T_BUC_TIMESTAMP IF EXISTS;
DROP TABLE T_BUC_VARCHAR IF EXISTS;
DROP TABLE T_BUC_SORT2 IF EXISTS;
DROP TABLE T_BUC_SORT3 IF EXISTS;
DROP TABLE T_BUC_EX1 IF EXISTS;
DROP TABLE EX_PART_BUC IF EXISTS;

-- 创建外部表，10条数据
CREATE EXTERNAL TABLE EX_PART_BUC(TBIGINT BIGINT,TINT INT,TSMALLINT SMALLINT,TREAL REAL,TDOUBLE DOUBLE,TFLOAT FLOAT,TDECIMAL DECIMAL(10,2),TNUMERIC NUMERIC(10,4),TDATE DATE,TTIMESTAMP TIMESTAMP,TBOOL BOOLEAN,TCHAR CHAR(30),TVARCHAR VARCHAR(255))
location ('HDFSRPC_URL/partition_bucket/partition_bucket.csv') FORMAT 'csv' (DELIMITER ',');

-- 创建分桶表，以int类型列排序
CREATE TABLE T_BUC_INT (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_INT;
-- 插入数据，2个分桶，一个桶有9条数据，一个桶有1条数据
INSERT INTO T_BUC_INT SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_INT
SELECT * FROM T_BUC_INT;

-- 创建分桶表，以VARCHAR类型排序
CREATE TABLE T_BUC_BOOLEAN (A BOOLEAN, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (C) INTO 3 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_BOOLEAN;
-- 插入数据，2个分桶，一个桶4条false数据，一个桶6条true数据
INSERT INTO T_BUC_BOOLEAN SELECT TBOOL, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_BOOLEAN
SELECT * FROM T_BUC_BOOLEAN;

-- 创建分桶表，以char类型排序
CREATE TABLE T_BUC_CHAR (A CHAR(30), B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 2 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_CHAR;
-- 插入数据，分桶字段值全都一致，1个分桶
INSERT INTO T_BUC_CHAR SELECT TCHAR, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_CHAR
SELECT * FROM T_BUC_CHAR;

-- 创建分桶表，以date类型排序
CREATE TABLE T_BUC_DATE (A DATE, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 1 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_DATE;
-- 插入数据，1个分桶
INSERT INTO T_BUC_DATE SELECT TDATE, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_DATE
SELECT * FROM T_BUC_DATE;

-- 创建分桶表，以decimal类型排序
CREATE TABLE T_BUC_DECIMAL (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (B) SORTED BY (B) INTO 5 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_DECIMAL;
-- 插入数据，10条数据平均分到5个桶
INSERT INTO T_BUC_DECIMAL SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_DECIMAL
SELECT * FROM T_BUC_DECIMAL;

-- 创建分桶表，以double类型排序
CREATE TABLE T_BUC_DOUBLE (A DOUBLE, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 10 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_DOUBLE;
-- 插入数据，10条数据非平均分到5个桶
INSERT INTO T_BUC_DOUBLE SELECT TDOUBLE, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_DOUBLE
SELECT * FROM T_BUC_DOUBLE;

-- 创建分桶表，以float类型排序
CREATE TABLE T_BUC_FLOAT (A FLOAT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 6 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_FLOAT;
-- 插入数据，10条数据非平均分到5个桶
INSERT INTO T_BUC_FLOAT SELECT TFLOAT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_FLOAT
SELECT * FROM T_BUC_FLOAT;

-- 创建分桶表，以NUMERIC类型排序
CREATE TABLE T_BUC_NUMERIC (A NUMERIC(10,4), B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 7 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_NUMERIC;
-- 插入数据，分桶字段值有null，4个分桶
INSERT INTO T_BUC_NUMERIC SELECT TNUMERIC, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_NUMERIC
SELECT * FROM T_BUC_NUMERIC;

-- 创建分桶表，以REAL类型排序
CREATE TABLE T_BUC_REAL (A REAL, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 8 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_REAL;
-- 插入数据，6个分桶
INSERT INTO T_BUC_REAL SELECT TREAL, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_REAL
SELECT * FROM T_BUC_REAL;

-- 创建分桶表，以SMALLINT类型排序
CREATE TABLE T_BUC_SMALLINT (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 9 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_SMALLINT;
-- 插入数据
INSERT INTO T_BUC_SMALLINT SELECT TSMALLINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_SMALLINT
SELECT * FROM T_BUC_SMALLINT;

-- 创建分桶表，以TIMESTAMP类型排序
CREATE TABLE T_BUC_TIMESTAMP (A TIMESTAMP, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A) INTO 13 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_TIMESTAMP;
-- 插入数据，8个分桶
INSERT INTO T_BUC_TIMESTAMP SELECT TTIMESTAMP, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_TIMESTAMP
SELECT * FROM T_BUC_TIMESTAMP;

-- 创建分桶表，以BOOL类型列分桶
CREATE TABLE T_BUC_VARCHAR (A BOOLEAN , B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (C) SORTED BY (A) INTO 997 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_VARCHAR;
-- 插入数据，9个分桶
INSERT INTO T_BUC_VARCHAR SELECT TBOOL, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_VARCHAR
SELECT * FROM T_BUC_VARCHAR;

-- 创建以2个字段排序的分桶表
CREATE TABLE T_BUC_SORT2 (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (A, B) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_SORT2;
-- 插入数据，2个分桶
INSERT INTO T_BUC_SORT2 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_BUC_SORT2
SELECT * FROM T_BUC_SORT2;

-- 创建以全部列字段排序的分桶表
CREATE TABLE T_BUC_SORT3 (A INT, B SMALLINT , C BIGINT) CLUSTERED BY (A) SORTED BY (A, B, C) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_SORT3;
-- 插入数据，2个分桶
INSERT INTO T_BUC_SORT3 SELECT TINT, TSMALLINT, TBIGINT FROM EX_PART_BUC;
-- 查询表T_BUC_SORT2
SELECT * FROM T_BUC_SORT3;

-- 创建以不存在字段排序的分桶表
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (D) INTO 4 BUCKETS;
-- SORTED拼写错误
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORT BY (B) INTO 4 BUCKETS;
-- 缺失括号
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY B INTO 4 BUCKETS;
-- SORTED BY位置错误
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) INTO 4 BUCKETS SORTED BY (B);
-- 缺失BY
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED (B) INTO 4 BUCKETS;
-- 创建以多个字段排序的分桶表
CREATE TABLE T_BUC (A INT, B DECIMAL(10,2), C VARCHAR(255)) CLUSTERED BY (A) SORTED BY (B, C) INTO 4 BUCKETS;

-- 创建外部分桶表T_BUC_EX1
CREATE EXTERNAL TABLE T_BUC_EX1(TINT INT,TDECIMAL DECIMAL(10,2),TVARCHAR VARCHAR(255))
LOCATION ('HDFSRPC_URL/partition_bucket1') FORMAT 'csv' (DELIMITER ',') CLUSTERED BY (TINT) SORTED BY (TINT) INTO 4 BUCKETS;
-- 查看创建表的ddl
SHOW CREATE TABLE T_BUC_EX1;
-- 插入数据，2个分桶
INSERT INTO T_BUC_EX1 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC; 
-- 查询表T_BUC_EX1
SELECT * FROM T_BUC_EX1;




