--Description:验证创建PALLAS表时数据类型的使用
--Date：2020-07-15
--Author：翟坤

SET ECHO ON
SET TIMING ON

-- 删除表
DROP TABLE T_SYNTAX_NORMAL IF EXISTS;
DROP TABLE T_SYNTAX IF EXISTS;

-- 正常
CREATE TABLE T_SYNTAX_NORMAL (A INT, B VARCHAR(255), C SMALLINT, D BIGINT, E BOOLEAN, F CHAR(10), G DECIMAL(10,2), H DOUBLE, I FLOAT, J REAL, L NUMERIC(4,2), M TIMESTAMP, N ARRAY) ENGINE PALLAS;

-- int类型拼错
CREATE TABLE T_SYNTAX (A INTGER, B VARCHAR(255)) ENGINE PALLAS;

-- varchar类型拼错
CREATE TABLE T_SYNTAX (A INTEGER, B VACHAR(255)) ENGINE PALLAS;

-- varchar长度为负数
CREATE TABLE T_SYNTAX (A INTEGER, B VARCHAR(-30)) ENGINE PALLAS;

-- varchar长度括号缺失
CREATE TABLE T_SYNTAX (A INTEGER, B VARCHAR30) ENGINE PALLAS;

-- varchar长度括号(缺失
CREATE TABLE T_SYNTAX (A INTEGER, B VARCHAR30)) ENGINE PALLAS;

-- smallint拼错
CREATE TABLE T_SYNTAX (A INTEGER, B SMALINT) ENGINE PALLAS;

-- bigint拼错
CREATE TABLE T_SYNTAX (A INTEGER, B BIGGINT) ENGINE PALLAS;

-- BOOL拼错
CREATE TABLE T_SYNTAX (A INTEGER, B BOLLEAN) ENGINE PALLAS;

-- char缺少长度
CREATE TABLE T_SYNTAX (A INTEGER, B CHAR) ENGINE PALLAS;

-- char长度为0
CREATE TABLE T_SYNTAX (A INTEGER, B CHAR(0)) ENGINE PALLAS;

-- date拼错
CREATE TABLE T_SYNTAX (A INTEGER, B DATA) ENGINE PALLAS;

-- decimal拼错
CREATE TABLE T_SYNTAX (A INTEGER, B DECMAL(10,2)) ENGINE PALLAS;

-- decimal总长度和小数部分之间缺少逗号
CREATE TABLE T_SYNTAX (A INTEGER, B DECIMAL(10 2)) ENGINE PALLAS;

-- double拼错
CREATE TABLE T_SYNTAX (A INTEGER, B DOUBLLE) ENGINE PALLAS;

-- FLOAT拼错
CREATE TABLE T_SYNTAX (A INTEGER, B FLAOT) ENGINE PALLAS;

-- REAL拼错
CREATE TABLE T_SYNTAX (A INTEGER, B REALL) ENGINE PALLAS;

-- NUMERIC拼错
CREATE TABLE T_SYNTAX (A INTEGER, B NUMBER(5,2)) ENGINE PALLAS;

-- TIMESTAMP拼错
CREATE TABLE T_SYNTAX (A INTEGER, B TIMETAMP) ENGINE PALLAS;

-- ARRAY前没有带类型
CREATE TABLE T_SYNTAX (A INTEGER, B ARRAY) ENGINE PALLAS;

-- ARRAY拼错
CREATE TABLE T_SYNTAX (A INTEGER, B VARCHAR(30) ARAY) ENGINE PALLAS;

-- ARRAY在类型前面
CREATE TABLE T_SYNTAX (A INTEGER, B ARRAY FLOAT) ENGINE PALLAS;








