--Description:join
--Date：2020-05-08
--Author：贾路遥

connect admin/123456

set timing on

set ECHO ON

set WHENEVER_SQLERROR CONTINUE

set termout off



--以下为两表进行inner join的测试用例
--单个等值join
--两表join,单个等值join,join字段类型为BIGINT
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TUNIQUE=B.TUNIQUE   limit 100;

--两表join,单个等值join,join字段类型为DOUBLE
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TDOUBLE=B.TDOUBLE  limit 100;

--两表join,单个等值join,join字段类型为DATE
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TDATE=B.TDATE  limit 100;

--两表join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TVARCHAR=B.TVARCHAR  limit 100;

--两表join,单个等值join,join字段类型为SMALLINT
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TSMALLINT=B.TSMALLINT  limit 100;

--两表join,单个等值join,join字段类型为INTEGER
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TINTEGER=B.TINTEGER  limit 100;

--两表join,单个等值join,join字段类型为REAL
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TREAL=B.TREAL  limit 100;

--两表join,单个等值join,join字段类型为TFLOAT
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TFLOAT=B.TFLOAT  limit 100;

--两表join,单个等值join,join字段类型为DECIMAL
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TDECIMAL=B.TDECIMAL  limit 100;

--两表join,单个等值join,join字段类型为NUMERIC
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TNUMERIC=B.TNUMERIC  limit 100;

--两表join,单个等值join,join字段类型为TIMESTAMP
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TTIMESTAMP=B.TTIMESTAMP  limit 100;

--两表join,单个等值join,join字段类型为BOOLEAN
--SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TBOOL=B.TBOOL  limit 100;

--两表join,单个等值join,join字段类型为CHAR
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TCHAR=B.TCHAR  limit 100;

--两表join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TVARCHAR=B.TVARCHAR  limit 100;

--多个等值join
--两表join,多个等值join组合,无过滤条件，包含DDL中所有字段,字段类型包含BIGINT,SMALLINT,INTEGER,REAL,DOUBLE,FLOAT,DECIMAL,NUMERIC,DATE,TIMESTAMP,BOOLEAN,CHAR,VARCHAR
SELECT A.*,B.* 
	FROM P1000 A 
	JOIN P5000 B 
	  ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT 
	    AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
		AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3 limit 100;
	
--两表join,多个等值join组合,3条过滤条件，过滤条件类型包括smallint,boolean,varchar,包含DDL中所有字段,字段类型包含BIGINT,SMALLINT,INTEGER,REAL,DOUBLE,FLOAT,DECIMAL,NUMERIC,DATE,TIMESTAMP,BOOLEAN,CHAR,VARCHAR
SELECT A.*,B.* FROM P1000 A 
	JOIN P5000 B 
	  ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
		AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
		AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3
	WHERE A.TSMALLINT BETWEEN 1 AND 1000
	  AND B.TBOOL=TRUE
	  AND A.TVARCHARIDX2 LIKE '%A%' limit 100;



--显式隐式转换

--两表join,单个等值join,显式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TINTEGER=cast(B.TDOUBLE AS int) limit 100;

--两表join,单个等值join,隐式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TINTEGER=B.TDOUBLE limit 100;

--两表join,显式隐式转换组合,TIMESTAMP&DATE
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) limit 100;

--两表join,多个等值join组合&显式隐式转换组合，4个条件
SELECT A.*,B.* FROM P1000 A JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) AND A.TDECIMAL=B.TDECIMAL AND A.TBOOL=B.TBOOL limit 100;

--以下为left join测试用例	
--单个等值join 
--out join,两表left join,单个等值join,join字段类型为BIGINT
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TUNIQUE=B.TUNIQUE limit 100;

--out join,两表left join,单个等值join,join字段类型为DOUBLE
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TDOUBLE=B.TDOUBLE limit 100;

--out join,两表left join,单个等值join,join字段类型为DATE
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TDATE=B.TDATE limit 100;

--out join,两表left join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TVARCHAR=B.TVARCHAR limit 100;

--out join,两表left join,单个等值join,join字段类型为SMALLINT
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TSMALLINT=B.TSMALLINT limit 100;

--out join,两表left join,单个等值join,join字段类型为INTEGER
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TINTEGER=B.TINTEGER limit 100;

--out join,两表left join,单个等值join,join字段类型为REAL
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TREAL=B.TREAL limit 100;

--out join,两表left join,单个等值join,join字段类型为TFLOAT
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TFLOAT=B.TFLOAT limit 100;

--out join,两表left join,单个等值join,join字段类型为DECIMAL
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TDECIMAL=B.TDECIMAL limit 100;

--out join,两表left join,单个等值join,join字段类型为NUMERIC
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TNUMERIC=B.TNUMERIC limit 100;

--out join,两表left join,单个等值join,join字段类型为TIMESTAMP
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TTIMESTAMP=B.TTIMESTAMP limit 100;

--out join,两表left join,单个等值join,join字段类型为BOOLEAN
--SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TBOOL=B.TBOOL limit 100;

--out join,两表left join,单个等值join,join字段类型为CHAR
SELECT A.*,B.* FROM P1000 A left join P5000 B ON A.TCHAR=B.TCHAR limit 100;


--多个等值join
--out join,两表left join,多个等值join组合,包含DDL中所有字段
SELECT A.*,B.* FROM P1000 A LEFT JOIN P5000 B ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
	AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
	AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3  limit 100;

--out join,两表left join,3条过滤条件，多个等值join组合，过滤条件类型包括numeric,int,float,包含DDL中所有字段
SELECT A.*,B.* FROM P1000 A 
	LEFT JOIN P5000 B 
	  ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
	  AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
	  AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3
	WHERE A.TNUMERIC NOT IN (6394.4060,6113.0566,7135.5794)
	  AND B.TINTEGER > 37843778
	  AND ((A.TFLOAT BETWEEN 1337.4699707031 AND 6847.7001953125) OR (A.TFLOAT BETWEEN 526.4699707031 AND 632.9600219727))
	   limit 100;

--显式隐式转换
--out join,两表left join,单个等值join,显式转换类型,INTEGER&DOUBLE	
SELECT A.*,B.* FROM P1000 A LEFT JOIN P5000 B ON A.TINTEGER=cast(B.TDOUBLE AS int) limit 100;
--out join,两表left JOIN,单个等值join,隐式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A LEFT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE limit 100;
--out join,两表left JOIN,显式隐式转换组合,TIMESTAMP&DATE
SELECT A.*,B.* FROM P1000 A LEFT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) limit 100;
--out join,两表left JOIN,多个等值join组合&显式隐式转换组合，4个条件
SELECT A.*,B.* FROM P1000 A LEFT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) AND A.TDECIMAL=B.TDECIMAL AND A.TBOOL=B.TBOOL limit 100;


--以下为right join测试用例
--单个等值join
--out join,两表right join,单个等值join,join字段类型为BIGINT
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TUNIQUE=B.TUNIQUE limit 100;

--out join,两表right join,单个等值join,join字段类型为DOUBLE
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TDOUBLE=B.TDOUBLE limit 100; 

--out join,两表right join,单个等值join,join字段类型为DATE
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TDATE=B.TDATE limit 100;

--out join,两表right join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TVARCHAR=B.TVARCHAR limit 100;

--out join,两表right join,单个等值join,join字段类型为SMALLINT
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TSMALLINT=B.TSMALLINT limit 100;

--out join,两表right join,单个等值join,join字段类型为INTEGER
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TINTEGER=B.TINTEGER limit 100;

--out join,两表right join,单个等值join,join字段类型为REAL
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TREAL=B.TREAL limit 100;

--out join,两表right join,单个等值join,join字段类型为TFLOAT
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TFLOAT=B.TFLOAT limit 100;

--out join,两表right join,单个等值join,join字段类型为DECIMAL
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TDECIMAL=B.TDECIMAL limit 100;

--out join,两表right join,单个等值join,join字段类型为NUMERIC
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TNUMERIC=B.TNUMERIC limit 100;

--out join,两表right join,单个等值join,join字段类型为TIMESTAMP
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TTIMESTAMP=B.TTIMESTAMP limit 100;


--out join,两表right join,单个等值join,join字段类型为CHAR
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TCHAR=B.TCHAR limit 100;

--out join,两表right join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TVARCHAR=B.TVARCHAR limit 100;

--多个等值join
--out join,两表right join,多个等值join组合,包含DDL中所有字段
SELECT A.*,B.* FROM P1000 A right join P5000 B ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
	AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
	AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3
	limit 100;

--out join,两表right join,4条过滤条件，过滤条件中的类型包含bigint,real,double,decimal,多个等值join组合,包含DDL中所有字段
SELECT A.*,B.* FROM P1000 A 
	right join P5000 B 
	  ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
		AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
		AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3
	WHERE B.TUNIQUE > 100000
	  AND A.TREAL NOT IN (214.57,2634.13,2862.67,1767.11)
	  AND A.TDOUBLE <> 1703.51
	  AND A.TDECIMAL > 5135.00
	  limit 100;

--显式隐式转换
--out join,两表right join,单个等值join,显式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A RIGHT JOIN P5000 B ON A.TINTEGER=cast(B.TDOUBLE AS int) limit 100;

--out join,两表right join,单个等值join,隐式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A RIGHT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE limit 100;

--out join,两表right join,显式隐式转换组合,TIMESTAMP&DATE
SELECT A.*,B.* FROM P1000 A RIGHT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) limit 100;

--out join,两表right join,多个等值join组合&显式隐式转换组合，4个条件
SELECT A.*,B.* FROM P1000 A RIGHT JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) AND A.TDECIMAL=B.TDECIMAL AND A.TBOOL=B.TBOOL limit 100; 


--以下为full outer join测试用例
--out join,两表full outer join,单个等值join,join字段类型为BIGINT
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TUNIQUE=B.TUNIQUE limit 100;

--out join,两表full outer join,单个等值join,join字段类型为DOUBLE
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TDOUBLE=B.TDOUBLE limit 100;

--out join,两表full outer join,单个等值join,join字段类型为DATE
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TDATE=B.TDATE limit 100;

--out join,两表full outer join,单个等值join,join字段类型为VARCHAR
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TVARCHAR=B.TVARCHAR limit 100;

--out join,两表full outer join,单个等值join,join字段类型为SMALLINT
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TSMALLINT=B.TSMALLINT limit 100;

--out join,两表full outer join,单个等值join,join字段类型为INTEGER
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TINTEGER=B.TINTEGER limit 100;

--out join,两表full outer join,单个等值join,join字段类型为REAL
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TREAL=B.TREAL limit 100;

--out join,两表full outer join,单个等值join,join字段类型为TFLOAT
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TFLOAT=B.TFLOAT limit 100;

--out join,两表full outer join,单个等值join,join字段类型为DECIMAL
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TDECIMAL=B.TDECIMAL limit 100;

--out join,两表full outer join,单个等值join,join字段类型为NUMERIC
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TNUMERIC=B.TNUMERIC limit 100;

--out join,两表full outer join,单个等值join,join字段类型为TIMESTAMP
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TTIMESTAMP=B.TTIMESTAMP limit 100;

--out join,两表full outer join,单个等值join,join字段类型为CHAR
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TCHAR=B.TCHAR limit 100;


--多个等值join
--out join,两表full outer join,多个等值join组合,包含DDL中所有字段
SELECT A.*,B.* FROM P1000 A full outer join P5000 B ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
	AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
	AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3 limit 100;

--out join,两表full outer join,2条过滤条件,过滤条件中包含timestamp和date类型，多个等值join组合,包含DDL中所有字段
SELECT A.*,B.* 
	FROM P1000 A 
	full outer join P5000 B 
	  ON A.TUNIQUE=B.TUNIQUE AND A.TSMALLINT=B.TSMALLINT AND A.TINTEGER=B.TINTEGER AND A.TBIGINT=B.TBIGINT
		AND A.TREAL=B.TREAL AND A.TDOUBLE=B.TDOUBLE AND A.TFLOAT=B.TFLOAT AND A.TDECIMAL=B.TDECIMAL AND A.TNUMERIC=B.TNUMERIC AND A.TDATE=B.TDATE AND A.TTIMESTAMP=B.TTIMESTAMP AND A.TBOOL=B.TBOOL AND A.TCHAR=B.TCHAR AND A.TVARCHAR=B.TVARCHAR
		AND A.TCHARIDX1=B.TCHARIDX1 AND A.TCHARIDX2=B.TCHARIDX2 AND A.TCHARIDX3=B.TCHARIDX3 AND A.TVARCHARIDX1=B.TVARCHARIDX1 AND A.TVARCHARIDX2=B.TVARCHARIDX2 AND A.TVARCHARIDX3=B.TVARCHARIDX3
	WHERE month(TIMESTAMP(A.TTIMESTAMP))=7
		  AND  WEEKOFYEAR(A.TDATE)=8
		  limit 100;
				
--显式隐式转换
--out join,两表full outer join,单个等值join,显式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A FULL OUTER JOIN P5000 B ON A.TINTEGER=cast(B.TDOUBLE AS int)  limit 100;

--out join,两表full outer join,单个等值join,隐式转换类型,INTEGER&DOUBLE
SELECT A.*,B.* FROM P1000 A FULL OUTER JOIN P5000 B ON A.TINTEGER=B.TDOUBLE  limit 100;

--out join,两表full outer join,显式隐式转换组合,TIMESTAMP&DATE
SELECT A.*,B.* FROM P1000 A FULL OUTER JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) limit 100;

--out join,两表full outer join,多个等值join组合&显式隐式转换组合，4个条件
SELECT A.*,B.* FROM P1000 A FULL OUTER JOIN P5000 B ON A.TINTEGER=B.TDOUBLE AND A.TTIMESTAMP=cast(B.TDATE AS TIMESTAMP) AND A.TDECIMAL=B.TDECIMAL AND A.TBOOL=B.TBOOL limit 100;


--以下为并集的测试用例
--并集，两个表进行并集操作，包含所有的行
SELECT * FROM P1000
UNION ALL
SELECT * FROM P5000 limit 100;

--并集，两个表进行并集操作，包含所有的行,使用过滤条件,过滤条件包括date，smallint
SELECT * FROM P1000 A WHERE A.TDATE='2018-05-28'
UNION ALL
SELECT * FROM P5000 B WHERE B.TSMALLINT BETWEEN 0 AND 9090 limit 100;

--并集，两个表进行并集操作，删除重复的行
SELECT * FROM P1000 
UNION
SELECT * FROM P5000 limit 100;

--并集，两个表进行并集操作，删除重复的行,使用过滤条件,过滤条件包括date，smallint
SELECT * FROM P1000 A WHERE A.TDATE='2018-05-28'
UNION 
SELECT * FROM P5000 B WHERE B.TSMALLINT BETWEEN 0 AND 9090 limit 100;

--以下为交集的测试用例
--交集，两表进行交集操作
SELECT * FROM P1000 
INTERSECT
SELECT * FROM P5000 limit 100;

--交集，两个表进行交集操作，使用过滤条件,过滤条件包括date，smallint
SELECT * FROM P1000 A WHERE A.TDATE='2018-05-28'
INTERSECT
SELECT * FROM P5000 B WHERE B.TSMALLINT BETWEEN 0 AND 9090 limit 100;
© 2020 GitHub, Inc.
