set echo on
set timing on

connect admin/123456
DROP TABLE TKE2 IF EXISTS;
CREATE TABLE TKE2
(ID INTEGER,
 NAME VARCHAR(20)
);
sleep 30
INSERT INTO TKE2 VALUES(1,'HELLO');
INSERT INTO TKE2 VALUES(2,'LALAL');
COMMIT;
SELECT * FROM TKE2 ORDER BY ID;
