--    Description: 测试资源管控
--    Date:         2020-06-12
--    Author:       丁婷
set echo on

--398 LDBX033-02 LDBX033-03 Resource control through resource groups

DROP resource group resource_group_test_001 if exists;

CREATE RESOURCE GROUP resource_group_test_001 GLOBAL PERCENT 100, GLOBAL MIN PERCENT 20;

SELECT resource_group_name,cpu_used,RESOURCE_GLOBAL_PRECENT,RESOURCE_GLOBAL_MIN_PERCENTAGE
FROM information_schema.SYSTEM_RESOURCE_GROUP  where RESOURCE_GROUP_NAME='RESOURCE_GROUP_TEST_001';

DROP resource group RESOURCE_GROUP_TEST_001 if exists;

DROP RESOURCE GROUP RESOURCE_GROUP_TEST_002 if exists;

create resource group RESOURCE_GROUP_TEST_002 EXECUTOR CPU 1,MANAGER MEMORY 1G, EXECUTOR MEMORY 1G,EXECUTOR NUMBER 1;

SELECT resource_group_name,memory_used/1024/1024/1024,cpu_used,RESOURCE_GLOBAL_PRECENT,RESOURCE_GLOBAL_MIN_PERCENTAGE,
RESOURCE_MANAGERMEMORY/1024/1024/1024,RESOURCE_EXECUTORMEMORY/1024/1024/1024,RESOURCE_EXECUTORCORES,RESOURCE_NUMEXECUTORS
FROM information_schema.SYSTEM_RESOURCE_GROUP  where RESOURCE_GROUP_NAME='RESOURCE_GROUP_TEST_002';

alter resource group RESOURCE_GROUP_TEST_002 set MANAGER MEMORY 2g, EXECUTOR MEMORY 2g;

SELECT resource_group_name,memory_used/1024/1024/1024,cpu_used,RESOURCE_GLOBAL_PRECENT,RESOURCE_GLOBAL_MIN_PERCENTAGE,
RESOURCE_MANAGERMEMORY/1024/1024/1024,RESOURCE_EXECUTORMEMORY/1024/1024/1024,RESOURCE_EXECUTORCORES,RESOURCE_NUMEXECUTORS
FROM information_schema.SYSTEM_RESOURCE_GROUP  where RESOURCE_GROUP_NAME='RESOURCE_GROUP_TEST_002';

DROP RESOURCE GROUP RESOURCE_GROUP_TEST_002 if exists;

DROP RESOURCE GROUP RESOURCE_GROUP_TEST_003 if exists;

CREATE RESOURCE GROUP RESOURCE_GROUP_TEST_003 GLOBAL PERCENT 50, GLOBAL MIN PERCENT 10, MANAGER MEMORY 2g, EXECUTOR MEMORY 1g, EXECUTOR CPU 3;

ALTER RESOURCE GROUP RESOURCE_GROUP_TEST_003 SET GLOBAL PERCENT 100, GLOBAL MIN PERCENT 10, MANAGER MEMORY 0g, EXECUTOR MEMORY 0g, EXECUTOR CPU 0;

SELECT resource_group_name,cpu_used,RESOURCE_GLOBAL_PRECENT,RESOURCE_GLOBAL_MIN_PERCENTAGE,
RESOURCE_MANAGERMEMORY/1024/1024/1024,RESOURCE_EXECUTORMEMORY/1024/1024/1024,RESOURCE_EXECUTORCORES
FROM information_schema.SYSTEM_RESOURCE_GROUP  where RESOURCE_GROUP_NAME='RESOURCE_GROUP_TEST_003';

DROP RESOURCE GROUP RESOURCE_GROUP_TEST_003 if exists;



