--Description: doc 11 chapter view
--Date：2020-07-13
--Author：满意

CREATE VIEW EMP_30
AS SELECT EMPNO
,ENAME
,SAL
FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_30;

CREATE VIEW EMP_DEPT
AS SELECT e.EMPNO
,e.ENAME
,e.JOB
,e.SAL
,e.COMM
,e.DEPTNO
,d.DNAME
,d.LOC
FROM EMP e
INNER JOIN DEPT d
ON e.DEPTNO = d.DEPTNO;

SELECT * FROM EMP_DEPT;

CREATE VIEW EMP_RENAME
AS SELECT EMPNO E_NO
,DEPTNO D_NO
,ENAME E_NAME
,SAL E_SAL
FROM EMP
WHERE DEPTNO = 20;

SELECT * FROM EMP_RENAME;

CREATE VIEW EMP_SAL
AS SELECT DEPTNO AS DEPT_NO
,SUM (SAL) AS SAL_TOTAL
,AVG (SAL) AS SAL_AVG
,MAX (SAL) AS SAL_MAX
,MIN (SAL) AS SAL_MIN
FROM EMP
GROUP BY DEPTNO;

SELECT * FROM EMP_SAL;

CREATE VIEW EMP_SAL2
AS SELECT DEPTNO AS DEPT_NO
,SUM (SAL) AS SAL_TOTAL
,AVG (SAL) AS SAL_AVG
,MAX (SAL) AS SAL_MAX
,MIN (SAL) AS SAL_MIN
FROM emp
GROUP BY DEPTNO
HAVING AVG(SAL) < 2000 ;

SELECT * FROM EMP_SAL2;


