--Description: doc 9.5.5 link hive
--Date：2020-07-14
--Author：丁婷

GRANT CREATE_SCHEMA TO USER;
CREATE DATABASE LINK HIVE_LINK CONNECT TO 'hive' IDENTIFIED BY 'hive'
USING 'hive' PROPERTIES ('maxActive':'5','database':'default');

RELOAD DATABASE LINK HIVE_LINK;

DROP DATABASE LINK HIVE_LINK CASCADE;
修改HIVE DATABASE LINK
语法： ALTER DATABASE LINK <DBLINK_NAME> CONNECT TO 'hive' IDENTIFIED BY 'hive' USING 'hive'
PROPERTIES ('database':'default'[, 'maxActive':'<value>'])
TIP 上述语法中的user,password,url均固定为hive
例:
214
GRANT CREATE_SCHEMA TO USER;
ALTER DATABASE LINK HIVE_LINK CONNECT TO 'hive' IDENTIFIED BY 'hive' USING
'hive' PROPERTIES ('maxActive':'5','database':'default');
当dblink里用到的用户的用户名或者密码被改变时，若想继续使用link,则需要用到ALTER TIP DATABASE LINK语句
通过HIVE DATABASE LINK操作HIVE中的对象
创建表
CREATE TABLE HIVE_LINK.TEST (
ID INT,
NAME VARCHAR(20));
插入数据
INSERT INTO HIVE_LINK.TEST VALUES (1,'zs');
更新数据
UPDATE HIVE_LINK.TEST SET ID == 2; 删除数据
DELETE FROM HIVE_LINK.TEST; 查询表
SELECT * FROM HIVE_LINK.TEST; 创建视图
CREATE VIEW HIVE_LINK.VIEW1 AS SELECT * HIVE_LINK.TEST; 查询视图
215
SELECT * FROM HIVE_LINK.VIEW1;
HIVE DATABASE LINK的权限控制 将对表的操作权限授予给用户。
GRANT INSERT,SELECT,UPDATE,DELETE ON HIVE_LINK.TEST TO USER;