connect admin/123456
DROP TABLE TKE2 IF EXISTS;
CREATE TABLE TKE2
(ID INTEGER,
 NAME VARCHAR(20)
);
INSERT INTO TKE2 VALUES(1,'HELLO');
INSERT INTO TKE2 VALUES(2,'LALAL');
COMMIT;
DROP TABLE TKE3 IF EXISTS;
CREATE TABLE TKE3
(ID INTEGER,
 NAME VARCHAR(20)
);
INSERT INTO TKE3 VALUES(1,'Sun1');
INSERT INTO TKE3 VALUES(2,'Sun2');
COMMIT;
DROP TABLE TKE4 IF EXISTS;
CREATE TABLE TKE4
(ID INTEGER,
 NAME VARCHAR(20)
);
INSERT INTO TKE4 VALUES(1,'Moon1');
INSERT INTO TKE4 VALUES(2,'Moon2');
COMMIT;
SELECT * FROM TKE2 ORDER BY ID;
SELECT * FROM TAB1 ORDER BY ID;

