= merge into功能测试方案
:doctype: article
:encoding: utf-8
:lang: zh
:toc:
:numbered:

==  编写时间

2019-09-01

==  测试时间

2019-09-01至2019-09-06

==  测试内容

merge into功能测试

== 测试思路

=== update和insert into组合

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 UPDATE SET
 e.ename = n.ename,
 e.sal = n.sal,
 e.mgr = n.mgr,
 e.deptno = n.deptno
WHEN NOT MATCHED THEN
 INSERT ( e.empno, e.ename, e.sal, e.mgr, e.deptno )
 VALUES ( n.empno, n.ename, n.sal, n.mgr, n.deptno );

=== delete和insert into组合

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 delete 
WHEN NOT MATCHED THEN
 INSERT ( e.empno, e.ename, e.sal, e.mgr, e.deptno )
 VALUES ( n.empno, n.ename, n.sal, n.mgr, n.deptno );

=== 省略update或delete字句

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN NOT MATCHED THEN
 INSERT ( e.empno, e.ename, e.sal, e.mgr, e.deptno )
 VALUES ( n.empno, n.ename, n.sal, n.mgr, n.deptno );

=== 省略insert into字句

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 delete 
 
** 或

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 UPDATE SET
 e.ename = n.ename,
 e.sal = n.sal,
 e.mgr = n.mgr,
 e.deptno = n.deptno

=== UPDATE后面接delete字句

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 UPDATE SET
 e.ename = n.ename,
 e.sal = n.sal,
 e.mgr = n.mgr,
 e.deptno = n.deptno
DELETE WHERE (n.sal >= 5000)
WHEN NOT MATCHED THEN
 INSERT ( e.empno, e.ename, e.sal, e.mgr, e.deptno )
 VALUES ( n.empno, n.ename, n.sal, n.mgr, n.deptno );
 

=== UPDATE set后面接表达式

MERGE INTO emp AS e
 USING (SELECT * FROM new_hire) AS n
 ON e.empno = n.empno
WHEN MATCHED THEN
 UPDATE SET
 e.ename = n.ename+1,
 e.sal = 10,
 e.mgr = abs(n.mgr),
 e.deptno = n.deptno
WHEN NOT MATCHED THEN
 INSERT ( e.empno, e.ename, e.sal, e.mgr, e.deptno )
 VALUES ( n.empno, n.ename, n.sal, n.mgr, n.deptno );
 
=== 表和表

MERGE INTO table A
USING table B

=== 表和QUERY

MERGE INTO table A
USING QUERY

=== QUERY和表

MERGE INTO table QUERY
USING table B

=== QUERY和QUERY

MERGE INTO  QUERY
USING QUERY

 
 
 
