= Pallas Complex data types测试计划
:doctype: article
:encoding: utf-8
:lang: zh
:toc:
:numbered:


## 编写时间

2019-06-24

## 测试版本

linkoopdb-2.0.0.257-20190620

## 测试时间

2019-05-14至2019-05-17

## 测试内容

测试pallas复杂数据类型，其中包括BLOB，CLOB，数组及自定义数据类型 +
https://github.com/datapps/linkoopdb/issues/1297

## 测试思路

### 数组

<1> 创建DB所支持的所有数据类型的数组在同一张表内，分别插入相应的数据，查询数组中每个元素的值是否与插入的数据一致 +
 
<2> 在上一张表的基础上新增新的数组类型的字段，然后插入数据，查看实际结果与预期是否一致 +
 
<3> 修改数组的类型，如数值型数组转字符型数组等，查看实际结果与预期是否一致 +
 
<4> 创建上述表的视图，然后查询视图的实际结果与预期是否一致 +
 
### BLOB，CLOB类型

<1> 使用java jdbc的方式对BLOB数据类型的表中插入数据，其中BLOB类型插入的数据类型有byte数组，图片，视频等，查看是否能正常插入及结果是否正确 +
  
<2> 使用java jdbc的方式把BLOB数据类型的表中的数据导出为byte数组，图片，视频等，查看导出的byte数组，图片，视频等是否正确 +
  
<3> 使用java jdbc的方式对BLOB数据类型的表中插入500kb，1G，1.5G，2G的二进制数据，查看是否能插入成功且导出后正确 +

<4> 使用java jdbc的方式对BLOB数据类型的表中插入2.5G的视频，查看是否能插入成功且导出后是否正确 +

<5> 使用java jdbc的方式对BLOB，CLOB数据类型的表进行嵌套查询，修改，删除等操作，查看结果是否正确，在cli中查询表结果，查看是否与jdbc得到的结果是否一致 +

<6> 使用java jdbc的方式对CLOB数据类型的表中插入数据，其中BLOB类型插入的数据类型有字符型，文本型等，查看是否能正常插入及结果是否正确 +


### 基础UDT   

<1> 创建UDT以别名的形式重新定义已有的数据类型，查看新建的UDT是否能正常使用以及正常删除 +
  
<2> 创建多个基础的UDT，然后进行组合，形成新的UDT，查看新建的UDT是否能正常使用以及正常删除 +
  
<3> 创建复杂的UDT，然后进行组合，形成新的UDT，查看新建的UDT是否能正常使用以及正常删除 +
  
<4> 修改已创建的UDT的数据类型，查看是否能修改成功，是否能正常使用及正常删除 +
  


## 测试可能遇到的问题

<1> 使用java jdbc时，因特殊情况而导致程序并未正常关闭连接池，DB的log则会一直提示nosql，且用jdbc方式创建的表等无法使用。只能通过删除元数据库的相应信息，然后重启db才能解决 +
