= 交接内容说明
:doctype: article
:encoding: utf-8
:lang: zh
:toc:
:numbered:

== HA环境说明

LDB HA环境所在服务器IP：node1,node2,node9

LDB部署位置：test_ha用户家目录

HA测试方案位置：

HA自动化测试框架和方案位置（代码和文档）：


== CDH测试集群位置

CDH 6.0.0所在服务器IP（集群，3个）：192.168.1.91，192.168.1.92，192.168.1.93

安装CDH 6.0.0所在目录：/opt/cloudera/

CHD访问地址和端口：192.168.1.91:7183


CDH 5.14所在服务器IP（集群，3个）：192.168.1.112,192.168.1.113,192.168.1.114

安装CDH 5.14所在目录：/opt/cloudera/

CHD访问地址和端口：192.168.1.112:7183

== studio API测试

测试用例位置：https://github.com/datapps/linkoop-auto-test/blob/master/linkoopdb/studio/studio-api.jmx

studio API查看地址和端口：http://node9:28510/swagger-ui/index.html

jenkins上自动执行studio api的测试job地址：http://node9:8888/view/LinkoopDB%20Test/job/linkoop-studio-apiTest/

jenkins上api测试报告地址：http://node9:8888/view/LinkoopDB%20Test/job/linkoop-studio-apiTest/LinkoopDB_20Test_20Report/


== 实施项目

=== 中投保

项目客户需求文档位置：https://github.com/datapps/linkoop-auto-test/tree/master/testdoc/ZTB/%E4%B8%AD%E6%8A%95%E4%BF%9D%E9%A1%B9%E7%9B%AE

客户环境连接方式及用户名密码：https://github.com/datapps/linkoop-auto-test/blob/master/testdoc/ZTB/%E4%B8%AD%E6%8A%95%E4%BF%9D%E9%A1%B9%E7%9B%AE/%E4%B8%80%E6%9C%9F/%E4%B8%AD%E6%8A%95%E4%BF%9D%E9%A1%B9%E7%9B%AE.xlsx

客户流程和数据存放位置：http://node9:18510/#/tree?queryWord=&currPage=1&limit=50&sorts=lastModifiedTime&reverse&tagSelection=&other=%7B%22ts%22:1562729264549%7D

=== 武汉机场

项目客户需求文档位置：无

客户环境连接方式及用户名密码：mstsc,47.100.119.84:15552， 用户名：administrator,密码：Thjc123

客户流程和数据存放位置：/default/home/ADMIN/数据仓库备份

其他程序源码和使用说明存放位置：https://github.com/datapps/linkoop-auto-test/tree/master/testdoc/%E6%AD%A6%E6%B1%89%E6%9C%BA%E5%9C%BA%E9%A1%B9%E7%9B%AE%E8%B5%84%E6%96%99

连接数据仓库（oracle）的访问方式：
serviceName：datamarket
ip：172.26.78.133
port：1521
userName： ANALYSIS
password：2018102209

DLINK配置语句：jdbc:oracle:thin:@//172.26.78.133:1521/datamarket 

== 测试用例补全

分配的未覆盖到ldb需求对应测试用例补全：

测试用例case存放位置：

313：jdbc

756: regression/LDB_EXT_JDBC_LargeResultSet.jmx

399: regression/LDB_EXT_资源管控.jmx

749: regression/LDB_EXT_STREAM.jmx

750: regression/LDB_EXT_STREAM.jmx

1030: regression/LDB_EXT_STREAM.jmx

1031: regression/LDB_EXT_STREAM.jmx

1034: regression/LDB_EXT_Stream_RPC_AI.jmx

1149: regression/LDB_EXT_STREAM.jmx

1268: regression/LDB_EXT_STREAM.jmx

其他：需要手动测试或者需要借助studio

jdbc测试程序和工程位置：callSessionId
