= 机器学习端到端测试方案
:doctype: article
:encoding: utf-8
:lang: zh
:toc:
:numbered:

 

==  编写时间

2019-06-26

== 测试版本

2.0.0.M4

==  测试时间

2019-6-24至2019-6-26

==  测试思路


==  测试内容

此处用一个真实的案例来说明：

例如：根据美国人口普查数据集的公共人口普查数据，预测一个人的年收入是否超过5万美元

数据的来源：官方网站提供的csv文件

数据预处理：通过特征RFormula函数对原始数据集中的所有varchar类型的数据进行了onehot编码，并过滤了无效的数据（空值），再通过ChiSqSelector函数进行了一次特征的帅选（剔除相关性较小的变量）

模型训练：将上述处理后的数据的LABEL,SELECTFEATURES作为模型的输入列，然后创建决策树模型

模型预测：调用上述已经训练好的模型对预测数据集中的样本进行划分

模型评估：最后通过auc的值来评估该模型的精确度

=== 数据的输入

结构化数据：结构化数据可以看作是关系型数据库的一张表，每列都有清晰的定义，包含了数值型和类别型两种基本类型；每一行数据表示一个样本的信息。
非结构化数据：主要包括对文本和图片的处理

=== 数据的预处理

** 无量纲话
无量纲化使不同规格的数据转换到同一规格。常见的无量纲化方法有标准化（standard_scaler_transformer）、区间缩放法（minmax_scaler_transformer）、归一化处理（normalizer_transformer）

** 对定量特征二值化
定量特征二值化的核心在于设定一个阈值，大于阈值的赋值为1，小于等于阈值的赋值为0（binarizer_transformer）
 
** 对定性特征哑编码（onehotencoder_estimator_transformer）

** 缺失值处理（imputer_transformer）
 
=== 创建训练数据集

原始数据经过一系列的处理（数据的清洗和转换）得到了训练模型的数据，通常包括一个特征列和一个标签列
 
=== 模型训练 

在模型训练过程中可通过调整模型参数得值来尽可能的训练出一个最优的模型

=== 模型预测

通过已训练好的模型预测未来的走势

=== 模型评估

** 分类问题
混淆矩阵、准确率、精确率、召回率、AUC值等

** 回归问题
平均绝对误差（MAE）、平均平方误差（MSE）、均方根误差（RMSE）、决定系数（r方）等



