--Description:partition
--Date：2020-06-18
--Author：阮娜

SET ECHO ON
SET TIMING ON

-- 删除表
DROP TABLE T_PART_INT IF EXISTS;
DROP TABLE T_PART_BOOL IF EXISTS;
DROP TABLE T_PART_CHAR IF EXISTS;
DROP TABLE T_PART_DATE IF EXISTS;
DROP TABLE T_PART_DECIMAL IF EXISTS;
DROP TABLE T_PART_DOUBLE IF EXISTS;
DROP TABLE T_PART_FLOAT IF EXISTS;
DROP TABLE T_PART_NUMERIC IF EXISTS;
DROP TABLE T_PART_REAL IF EXISTS;
DROP TABLE T_PART_SMALLINT IF EXISTS;
DROP TABLE T_PART_TIMESTAMP IF EXISTS;
DROP TABLE T_PART_VARCHAR IF EXISTS;
DROP TABLE T_PART_BIGINT IF EXISTS;
DROP TABLE T_PART_ARRAY IF EXISTS;
DROP TABLE T_PART2 IF EXISTS;
DROP TABLE T_PART3 IF EXISTS;
DROP TABLE T_PART_MONTH IF EXISTS;
DROP TABLE T_PART_LEN IF EXISTS;
DROP TABLE T_PART_ABS IF EXISTS;
DROP TABLE T_PART_MOD IF EXISTS;
DROP TABLE T_PART_FLOOR IF EXISTS;
DROP TABLE T_PART_TODATE IF EXISTS;
DROP TABLE T_PART_DAY IF EXISTS;
DROP TABLE T_PART_ROUND IF EXISTS;
DROP TABLE T_PART2_FUNC2 IF EXISTS;
DROP TABLE T_PART2_FUNC1 IF EXISTS;
DROP TABLE T_EX_DATA IF EXISTS;
DROP TABLE T_PART_EX1 IF EXISTS;
DROP TABLE T_PART_PALLAS IF EXISTS;
DROP TABLE T_PART_1 IF EXISTS;
DROP TABLE T_PART_2 IF EXISTS;
DROP TABLE EX_PART_BUC IF EXISTS;
-- 删除视图
DROP VIEW V_PART IF EXISTS;
DROP VIEW V_PART_1 IF EXISTS;

-- 创建外部表，10条数据
CREATE EXTERNAL TABLE EX_PART_BUC(TBIGINT BIGINT,TINT INT,TSMALLINT SMALLINT,TREAL REAL,TDOUBLE DOUBLE,TFLOAT FLOAT,TDECIMAL DECIMAL(10,2),TNUMERIC NUMERIC(10,4),TDATE DATE,TTIMESTAMP TIMESTAMP,TBOOL BOOLEAN,TCHAR CHAR(30),TVARCHAR VARCHAR(255))
location ('HDFSRPC_URL/partition_bucket/partition_bucket.csv') FORMAT 'csv' (DELIMITER ',');

-- 创建分区表，以int类型列分区
CREATE TABLE T_PART_INT (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_INT;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_INT';
-- 插入数据
INSERT INTO T_PART_INT SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_INT
SELECT * FROM T_PART_INT;

-- 创建分区表，以boolean类型列分区
CREATE TABLE T_PART_BOOL (A BOOLEAN, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_BOOL;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_BOOL';
-- 插入数据，2个分区
INSERT INTO T_PART_BOOL SELECT TBOOL, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_BOOLEAN
SELECT * FROM T_PART_BOOL;

-- 创建分区表，以char类型列分区
CREATE TABLE T_PART_CHAR (A CHAR(30), B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_CHAR;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_CHAR';
-- 插入数据，分区字段值全都一致，1个分区
INSERT INTO T_PART_CHAR SELECT TCHAR, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_CHAR
SELECT * FROM T_PART_CHAR;

-- 创建分区表，以date类型列分区
CREATE TABLE T_PART_DATE (A DATE, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_DATE;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_DATE';
-- 插入数据，9个分区
INSERT INTO T_PART_DATE SELECT TDATE, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_DATE
SELECT * FROM T_PART_DATE;

-- 创建分区表，以decimal类型列分区
CREATE TABLE T_PART_DECIMAL (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (B);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_DECIMAL;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_DECIMAL';
-- 插入数据，10个分区
INSERT INTO T_PART_DECIMAL SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_DECIMAL
SELECT * FROM T_PART_DECIMAL;

-- 创建分区表，以double类型列分区
CREATE TABLE T_PART_DOUBLE (A DOUBLE, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_DOUBLE;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_DOUBLE';
-- 插入数据，10个分区
INSERT INTO T_PART_DOUBLE SELECT TDOUBLE, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_DOUBLE
SELECT * FROM T_PART_DOUBLE;

-- 创建分区表，以float类型列分区
CREATE TABLE T_PART_FLOAT (A FLOAT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_FLOAT;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_FLOAT';
-- 插入数据，10个分区
INSERT INTO T_PART_FLOAT SELECT TFLOAT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_FLOAT
SELECT * FROM T_PART_FLOAT;

-- 创建分区表，以NUMERIC类型列分区
CREATE TABLE T_PART_NUMERIC (A NUMERIC(10,4), B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_NUMERIC;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_NUMERIC';
-- 插入数据，分区字段值有null，null为一个分区，总共7个分区
INSERT INTO T_PART_NUMERIC SELECT TNUMERIC, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_NUMERIC
SELECT * FROM T_PART_NUMERIC;

-- 创建分区表，以REAL类型列分区
CREATE TABLE T_PART_REAL (A REAL, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_REAL;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_REAL';
-- 插入数据，10个分区
INSERT INTO T_PART_REAL SELECT TREAL, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_REAL
SELECT * FROM T_PART_REAL;

-- 创建分区表，以SMALLINT类型列分区
CREATE TABLE T_PART_SMALLINT (A SMALLINT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_SMALLINT;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_SMALLINT';
-- 插入数据，字段值不均匀，3个分区
INSERT INTO T_PART_SMALLINT SELECT TSMALLINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_SMALLINT
SELECT * FROM T_PART_SMALLINT;

-- 创建分区表，以TIMESTAMP类型列分区
CREATE TABLE T_PART_TIMESTAMP (A TIMESTAMP, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_TIMESTAMP;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_TIMESTAMP';
-- 插入数据，10个分区
INSERT INTO T_PART_TIMESTAMP SELECT TTIMESTAMP, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_TIMESTAMP
SELECT * FROM T_PART_TIMESTAMP;

-- 创建分区表，以VARCHAR类型列分区
CREATE TABLE T_PART_VARCHAR (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (C);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_VARCHAR;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_VARCHAR';
-- 插入数据，9个分区
INSERT INTO T_PART_VARCHAR SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_VARCHAR
SELECT * FROM T_PART_VARCHAR;

-- 创建分区表，以BIGINT类型列分区
CREATE TABLE T_PART_BIGINT (A BIGINT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_BIGINT;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_BIGINT';
-- 插入数据，10个分区
INSERT INTO T_PART_BIGINT SELECT TBIGINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART_BIGINT
SELECT * FROM T_PART_BIGINT;

-- 创建分区表，以ARRAY类型列分区（不支持）
CREATE TABLE T_PART_ARRAY (A INT ARRAY, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_ARRAY;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_ARRAY';
-- 插入数据，2个分区
INSERT INTO T_PART_ARRAY VALUES (ARRAY[1,2], 1.1, 'a'), (ARRAY[1,2], 2.2, 'b'), (ARRAY[2,3], 3.3, 'c');

-- 创建以2个字段分区的分区表
CREATE TABLE T_PART2 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A, C);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART2;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART2';
-- 插入数据
INSERT INTO T_PART2 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;
-- 查询表T_PART2
SELECT * FROM T_PART2;

-- 创建以所有字段分区的分区表
CREATE TABLE T_PART3 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A, B, C);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART3;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART3';
-- 插入数据：Cannot use all columns for partition columns;
INSERT INTO T_PART3 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC;

-- 创建以func(col)分区的分区表
CREATE TABLE T_PART_MONTH (A DATE, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (MONTH(A));
CREATE TABLE T_PART_LEN (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (LENGTH(C));
CREATE TABLE T_PART_ABS (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (ABS(A));
CREATE TABLE T_PART_MOD (A BIGINT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (MOD(A, 2));
CREATE TABLE T_PART_FLOOR (A FLOAT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (FLOOR(A));
CREATE TABLE T_PART_TODATE (A TIMESTAMP, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (TO_DATE(A));
CREATE TABLE T_PART_DAY (A TIMESTAMP, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (DAY(TO_DATE(A)));
CREATE TABLE T_PART_ROUND (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (ROUND(B));
-- 创建以多个func(col)分区的分区表
CREATE TABLE T_PART2_FUNC2 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (ABS(A), LENGTH(C));
-- 创建以func(col)和col分区的分区表
CREATE TABLE T_PART2_FUNC1 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A, LENGTH(C));

-- 创建以不存在字段分区的分区表
CREATE TABLE T_PART (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (D);
-- PARTITIONED拼写错误
CREATE TABLE T_PART (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTIONED BY (A);
-- 缺失括号
CREATE TABLE T_PART (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY A;
-- 缺失逗号
CREATE TABLE T_PART (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A C);
-- 缺失BY
CREATE TABLE T_PART (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED (A);

-- 创建外部分区表T_PART_EX1
CREATE EXTERNAL TABLE T_PART_EX1(TINT INT,TDECIMAL DECIMAL(10,2),TVARCHAR VARCHAR(255))
LOCATION ('HDFSRPC_URL/partition_bucket') FORMAT 'csv' (DELIMITER ',') PARTITIONED BY (TINT);
-- 查看创建表的ddl
SHOW CREATE TABLE T_PART_EX1;
-- 查看系统表中该表的分区字段
select PERIPHERAL_INFO from information_schema.system_tables where TABLE_NAME = 'T_PART_EX1';
-- 分批次插入数据
INSERT INTO T_PART_EX1 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC WHERE TBIGINT BETWEEN 1000001 AND 1000005; 
INSERT INTO T_PART_EX1 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC WHERE TBIGINT BETWEEN 1000006 AND 10000010;
-- 查询表T_PART_EX1
SELECT * FROM T_PART_EX1;

-- 全部读出外部分区表数据到内部表
CREATE TABLE T_EX_DATA (TINT INT,TDECIMAL DECIMAL(10,2),TVARCHAR VARCHAR(255));
INSERT INTO T_EX_DATA SELECT * FROM T_PART_EX1;
SELECT * FROM T_EX_DATA;

-- 创建分区pallas表
CREATE TABLE T_PART_PALLAS (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A) ENGINE PALLAS;

-- 使用分区表创建视图
CREATE VIEW V_PART AS SELECT * FROM T_PART_INT WHERE A = 7566;
-- 查询视图
SELECT * FROM V_PART;

-- 2个分区表union
CREATE TABLE T_PART_1 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
CREATE TABLE T_PART_2 (A INT, B DECIMAL(10,2), C VARCHAR(255)) PARTITIONED BY (A);
INSERT INTO T_PART_1 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC WHERE TBIGINT BETWEEN 1000001 AND 1000005;
INSERT INTO T_PART_2 SELECT TINT, TDECIMAL, TVARCHAR FROM EX_PART_BUC WHERE TBIGINT BETWEEN 1000006 AND 10000010;
SELECT * FROM T_PART_1;
SELECT * FROM T_PART_2;
SELECT A FROM T_PART_1 UNION SELECT A FROM T_PART_2;

-- 2个视图union
CREATE VIEW V_PART_1 AS SELECT * FROM T_PART_INT WHERE A = 7698;
SELECT * FROM V_PART_1;
SELECT * FROM V_PART UNION SELECT * FROM V_PART_1;