--Description:column_number
--Date：2020-06-09
--Author：阮娜

SET ECHO ON
SET TIMING ON

-- 删除P_10W_1S表
DROP TABLE IF EXISTS P_10W_1S;

-- 创建单个shard pallas表P_10W_1S
CREATE TABLE P_10W_1S(
ANTINUCLEUS INTEGER,EVENTFILE INTEGER,EVENTNUMBER INTEGER,
EVENTTIME DOUBLE,HISTFILE INTEGER,MULTIPLICITY INTEGER,
NABOVELB INTEGER,NBELOWLB INTEGER,NLB INTEGER,PRIMARYTRACKS INTEGER,
PRODTIME DOUBLE,PT FLOAT,RUNNUMBER INTEGER,VERTEXX FLOAT,VERTEXY FLOAT,VERTEXZ FLOAT
) PROPERTIES('linkoopdb.pallas.shard_number':'1') ENGINE PALLAS;

-- 有事务，插入10万条数据到pallas表
INSERT INTO P_10W_1S SELECT * FROM EX_RN_10W;

SELECT COUNT(*) FROM P_10W_1S;

-- 删除P_10W01_1S表
DROP TABLE IF EXISTS P_10W01_1S;

-- 创建单个shard pallas表P_10W01_1S
CREATE TABLE P_10W01_1S(
ANTINUCLEUS INTEGER,EVENTFILE INTEGER,EVENTNUMBER INTEGER,
EVENTTIME DOUBLE,HISTFILE INTEGER,MULTIPLICITY INTEGER,
NABOVELB INTEGER,NBELOWLB INTEGER,NLB INTEGER,PRIMARYTRACKS INTEGER,
PRODTIME DOUBLE,PT FLOAT,RUNNUMBER INTEGER,VERTEXX FLOAT,VERTEXY FLOAT,VERTEXZ FLOAT
) PROPERTIES('linkoopdb.pallas.shard_number':'1') ENGINE PALLAS;

-- 有事务，插入10万01条数据到pallas表
INSERT INTO P_10W01_1S SELECT * FROM EX_RN_10W01;

SELECT COUNT(*) FROM P_10W01_1S;


